Update test applications
konveyor/go-konveyor-tests pull request #127
Opened 2024-06-07 07:33 UTC by aufi

Consolidating samples Applications used for analysis tests to data pks started by Maayan.

Most used `TackleTestApp` now explicitly uses main git branch, there is also `gradle` branch expected for TackleTestAppGradle.

2024-06-07 07:37 UTC, aufi commented on data/application.go
> +			Branch: "gradle",
I'm not sure if the is right to have gradle branch or some other solution, feedback is welcome.

I was just thinking that having different test applications for different releases is not very handy for tests debugging and stability. Feeling as better to be able say that TestAppXY analysis works on release-0.2 and 0.3, but is broken on 0.4, than having the "same" application that behave differently across releases.

2024-06-09 08:48 UTC, mguetta1 requested changes

2024-06-09 08:48 UTC, mguetta1 commented on data/application.go
> +	TackleTestappBin = api.Application{
The application can be used not only for binary analysis.
I suggest using`TackleTestappPrivate`/`TackleTestappPublic`

2024-07-11 11:23 UTC, closed without merging

2024-07-11 11:23 UTC, aufi commented
Closing in favor of https://github.com/konveyor/go-konveyor-tests/pull/161