[RFR] Fix Day trader analysis
konveyor/go-konveyor-tests pull request #185
Opened 2024-10-12 15:54 UTC by nachandr

2024-10-12 16:20 UTC, nachandr commented
![Daytrader_api_oct11](https://github.com/user-attachments/assets/62feb846-bd88-4b89-8933-e7e7c4189ea8)

Screen shot of Jenkins run that shows that the analysis of the day trader app passed

2024-10-14 16:22 UTC, mguetta1 reviewed
Hi @nachandr thanks for the PR. Could you please add issue incidents as well?

2024-10-15 04:09 UTC, nachandr commented
> Hi @nachandr thanks for the PR. Could you please add issue incidents as well?

Issue incidents have been added.

2024-10-15 05:50 UTC, mguetta1 requested changes

2024-10-15 05:50 UTC, mguetta1 commented on analysis/tc_daytrader.go
> +					},
We usually check also incident message, could you please add it?

2024-10-18 08:21 UTC, aufi approved these changes
LGTM

2024-10-26 17:55 UTC, mguetta1 approved these changes

2024-10-28 18:16 UTC, merged