Introduce test stages
konveyor/go-konveyor-tests pull request #21
Opened 2023-09-01 09:08 UTC by aufi

To provide maximum information about the project functionality, tests exections were separated into three stages (0,1,2). From core functionality to nice to haves.

Updated github workflows, Makefile targets and README with description.

2023-09-01 10:20 UTC, aufi commented
Stage1 target depends on https://github.com/konveyor/go-konveyor-tests/pull/16

2023-09-01 11:15 UTC, aufi commented
@mguetta1 @sshveta @dymurray @fabianvf Hi, please take a look, I think it makes sense split test executions in this repo to stages to have (rock) solid stage 0, solid stage 1 and maybe experimental stage 2. More details are in README and Makefile. I'm interested in your feedback, thanks!

2023-09-01 17:13 UTC, fabianvf commented
@aufi This looks good to me, were there any tests that needed to be dropped or are we at test parity with the old analyzer now?

2023-09-03 07:01 UTC, mguetta1 requested changes
Thanks @aufi! I added few comments

2023-09-04 14:09 UTC, aufi commented
> @aufi This looks good to me, were there any tests that needed to be dropped or are we at test parity with the old analyzer now?

We had a very little of tests from past on analysis (Pathfinder example-1 app and Petclinic). Currently Petclinic w/hazelcast is not included in analysis test - will be added (in one of next PRs).

2023-09-05 06:02 UTC, mguetta1 commented on Makefile
> +	HUB_BASE_URL="http://${MINIKUBE_IP}/hub" go test -count=1 -v ./metrics/...
I see, thanks

2023-09-05 06:31 UTC, mguetta1 approved these changes
LGTM

2023-09-06 11:08 UTC, aufi commented
Merging with passing tier0.

2023-09-06 11:08 UTC, merged