[RFR] Update dependency check
konveyor/go-konveyor-tests pull request #221
Opened 2024-11-19 17:14 UTC by nachandr

2024-11-20 15:32 UTC, aufi commented
IIUC the aim of this PR is to not allow pass analysis test without specifying dependencies.

![image](https://github.com/user-attachments/assets/cb7a5dd0-ae1d-4da9-89cd-18d725b00c53)

I don't think this is something we want. Optional skip of Dependencies or Tags in test assertion (defined by the test case), looks as the right option to me.

For visiblity @mguetta1 @jmle

2024-11-20 20:20 UTC, mguetta1 commented
> IIUC the aim of this PR is to not allow pass analysis test without specifying dependencies.
> 
> ![image](https://private-user-images.githubusercontent.com/555381/388156681-cb7a5dd0-ae1d-4da9-89cd-18d725b00c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzM5NzgsIm5iZiI6MTczMjEzMzY3OCwicGF0aCI6Ii81NTUzODEvMzg4MTU2NjgxLWNiN2E1ZGQwLWFlMWQtNGRhOS04OWNkLTE4ZDcyNWIwMGM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQyMDE0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2Y1OTFjYmUzYzc0MzBkYTJlYWI3OTA4NWY4MWM4ODNlYjVmMjU4MDVmNDNhNWY3ZWNjZTc2NzIyMDliZDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DVvJsNNP8xyfPJDif5x1KslL_PL563kXtM_JApeZUB8)
> 
> I don't think this is something we want. Optional skip of Dependencies or Tags in test assertion (defined by the test case), looks as the right option to me.
> 
> For visiblity @mguetta1 @jmle

I saw the need for such change after that Igor reported this regression bug: https://issues.redhat.com/browse/MTA-4169
At that time I wondered if we were seeing it in the API tests as well and realized that deps check was skipped for this app

2024-11-21 06:02 UTC, nachandr commented
Hi @aufi , Thanks for reviewing the PR. I noticed that when dependencies(or tags) are not specified for a test and when the API request response returns dependencies (or tags), the test still passes . The code changes address this scenario.
 
 Analysis test will still pass when dependencies (or tags) are not specified in the test if the API response request returns the dependency/tag count as zero. For eg: The tier 2 run for this PR shows that the Apache Wicket analysis passed (This test doesn't have dependencies listed)



> IIUC the aim of this PR is to not allow pass analysis test without specifying dependencies.
> 
> ![image](https://private-user-images.githubusercontent.com/555381/388156681-cb7a5dd0-ae1d-4da9-89cd-18d725b00c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjkyNDMsIm5iZiI6MTczMjE2ODk0MywicGF0aCI6Ii81NTUzODEvMzg4MTU2NjgxLWNiN2E1ZGQwLWFlMWQtNGRhOS04OWNkLTE4ZDcyNWIwMGM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjAyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDIzZGUzNzhjMDRkMDYwYTBhNWVjMGYwMzJjYTdjOWE4MjkwODhmZTAyYjVmYTVhMDQ3MmMzOTkwYzFkNDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QUnMN3pE6YQRfkWUEudj3YwT6_4Z5AghooxVYTBw-Lc)
> 
> I don't think this is something we want. Optional skip of Dependencies or Tags in test assertion (defined by the test case), looks as the right option to me.
> 
> For visiblity @mguetta1 @jmle

Hi @aufi , Thanks for reviewing the PR. I noticed that when dependencies(or tags) are not specified for a test and when the API request response returns dependencies (or tags), the test still passes . The code changes address this scenario.

Analysis test will still pass when dependencies (or tags) are not specified in the test if the API response request returns
the dependency/tag count as zero.
For eg: The tier 2 run for this PR shows that the Apache Wicket analysis passed (This test doesn't have dependencies listed)
![Update_dependency](https://github.com/user-attachments/assets/33d96021-891d-4321-898a-f115853b7dc8)

2024-11-21 06:15 UTC, aufi commented
Understood, the question is if we need more assert empty dependencies list or ability to not check dependencies (in this "easy" way), deffering to others. @mguetta1 @sshveta

2024-11-21 09:32 UTC, mguetta1 requested changes

2024-12-12 21:51 UTC, nachandr commented
I've been busy with 7.2 release activities. I'll work on this PR early next week.

2025-01-28 15:29 UTC, nachandr commented
> Understood, the question is if we need more assert empty dependencies list or ability to not check dependencies (in this "easy" way), deffering to others. @mguetta1 @sshveta

@sshveta, Could you respond to this when you get a chance ?

2025-01-28 18:48 UTC, sshveta commented
I think we can just automate the bug that Igor reported https://issues.redhat.com/browse/MTA-4169 so that we don't miss it and leave the dependency check optional for rest of the test cases . @mguetta1 @aufi @nachandr

2025-01-29 20:34 UTC, nachandr commented
> I think we can just automate the bug that Igor reported https://issues.redhat.com/browse/MTA-4169 so that we don't miss it and leave the dependency check optional for rest of the test cases . @mguetta1 @aufi @nachandr
In bug MTA-4169  , Igor has reported that dependencies were not listed after the DayTrader application was analyzed . We have automation coverage for this . 

I will close this PR for now.

2025-02-24 16:31 UTC, closed without merging