[WIP] Analyze Coolstore app  with dependencies, Quarkus branch
konveyor/go-konveyor-tests pull request #229
Opened 2024-11-29 04:04 UTC by nachandr

2024-12-03 16:40 UTC, aufi approved these changes
I cannot validate if issues analysis results are fully correct, but from quick look, looks OK.

Better ask someone contributing to the application repo itself: https://github.com/konveyor-ecosystem/coolstore

2024-12-03 17:21 UTC, nachandr commented
Hi @jmle , @jwmatthews , Could you let us know if the analysis results look good ?

2024-12-03 19:19 UTC, nachandr commented
Note : The test for the analysis of the Coolstore  app is a tier 0 test and the test-tier0 check failed because Tackle couldn't be installed.

2024-12-13 08:58 UTC, jmle requested changes
We need to find out if the lack of issues is due to a bad execution of the tests, or a bug in the system.

2024-12-13 08:58 UTC, jmle commented on analysis/tc_coolstore_deps_quarkus.go
> +				},
With `cloud-readiness` and `jakarta-ee` we should see more results than this. There is something going on, but not sure if it's the test itself or something else. It looks as if the java provider wasn't starting up for some reason. This particular issue belongs to a rule that uses the built-in provider, not the java provider.

2024-12-13 15:03 UTC, jmle approved these changes
Looks good @nachandr , it makes sense that we're only getting one issue, since the `quarkus` branch has already been migrated.

2024-12-13 15:37 UTC, merged